### ISSUE TITLE
No checkbox to save password.

### ISSUE THREAD

**Issue by ubcool2ic** [mangstadt/emc-shopkeeper#4]
I sometimes like to update my emc shopkeeper without being logged in but i do not know my forum pass. So i have to be logged in to update. Adding an option to "Remember me" would be amazing.

**Comment by mangstadt** [comment]
Hey ubcool! :D

The login window used to have a "remember me" checkbox, but it basically didn't work, so I removed it.  For some reason (couldn't figure out why), the login token that the EMC website generates when EMC Shopkeeper logs in only lasts a few hours, so the "remember me" checkbox was basically useless.

**Comment by mangstadt** [comment]
Although, I could have it save your password instead.  That would certainly work.  Maybe I'll do that...

**Comment by ubcool2ic** [comment]
a check option is better at least in my opinion because some people do 
not like apps/programs that save passwords. But Thanks :)

------ Original Message ------

**Comment by mangstadt** [comment]
Implemented!
